# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: robot_a
  joint_model_group_pose: robot_a_ready
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - robot_a_waist
    - robot_a_shoulder
    - robot_a_elbow
    - robot_a_forearm_roll
    - robot_a_wrist_angle
    - robot_a_wrist_rotate
    - robot_a_gripper
    - robot_a_left_finger
    - robot_b_waist
    - robot_b_shoulder
    - robot_b_elbow
    - robot_b_forearm_roll
    - robot_b_wrist_angle
    - robot_b_wrist_rotate
    - robot_b_gripper
    - robot_b_left_finger
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  - name: robot_a_arm_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - robot_a_waist
      - robot_a_shoulder
      - robot_a_elbow
      - robot_a_forearm_roll
      - robot_a_wrist_angle
      - robot_a_wrist_rotate
  - name: robot_b_arm_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - robot_b_waist
      - robot_b_shoulder
      - robot_b_elbow
      - robot_b_forearm_roll
      - robot_b_wrist_angle
      - robot_b_wrist_rotate