# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 100

arm_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - robot_a_waist
    - robot_a_shoulder
    - robot_a_elbow
    - robot_a_forearm_roll
    - robot_a_wrist_angle
    - robot_a_wrist_rotate
  gains: # Required because we're controlling an effort interface
    robot_a_waist: {p: 100.0,  d: 1.0, i: 5.0}
    robot_a_shoulder: {p: 500.0,  d: 1.0, i: 10.0}
    robot_a_elbow: {p: 300.0,  d: 1.0, i: 10.0}
    robot_a_forearm_roll: {p: 100.0, d: 0.1, i: 3.0}
    robot_a_wrist_angle: {p: 100.0,  d: 0.1, i: 3.0}
    robot_a_wrist_rotate: {p: 100.0,  d: 0.1, i: 1.0}

  constraints:
    goal_time: 0.2
    robot_a_waist:
      goal: 0.1
      trajectory: 0.2
    robot_a_shoulder:
      goal: 0.2
      trajectory: 0.2
    robot_a_elbow:
      goal: 0.2
      trajectory: 0.2
    robot_a_forearm_roll:
      goal: 0.2
      trajectory: 0.2
    robot_a_wrist_angle:
      goal: 0.2
      trajectory: 0.2
    robot_a_wrist_rotate:
      goal: 0.2
      trajectory: 0.2


gripper_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - robot_a_left_finger
    - robot_a_right_finger
  gains:
    robot_a_left_finger: {p: 100.0,  d: 1.0, i: 0.0}
    robot_a_right_finger: {p: 100.0,  d: 1.0, i: 0.0}
